[package]
name = "echor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
assert_cmd = "2.0.13"
clap = { version = "4.5.20", features = ["derive"] }
predicates = "3.0.4"
pretty_assertions = "1.4.0"

[dev-dependencies]
serde = "1.0.214"
